[package]
name = "yt"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
#amethyst = {path = "/home/andrea/Workspace/git/amethyst", features=["vulkan"]}
amethyst = {path = "/home/andrea/Workspace/git/amethyst", features=["nightly", "vulkan"]}
rand = {version = "0.7"}
